//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSShippingLtd.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnualLeave
    {
        public int LeaveID { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<System.DateTime> EmployeeStartDate { get; set; }
        public Nullable<System.DateTime> EmployeeEndDate { get; set; }
        public Nullable<int> EmployeeManager_Id { get; set; }
        public Nullable<decimal> TotalLeavePerYear { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
