//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSShippingLtd.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeave
    {
        public int EmployeeLeaveId { get; set; }
        public Nullable<System.DateTime> LeaveStartDate { get; set; }
        public Nullable<System.DateTime> LeaveEndDate { get; set; }
        public string AdditionInfo { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<int> AuthorizedBy { get; set; }
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<decimal> TotalLeaveAuthorized { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Authorized { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
