//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSShippingLtd.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.AnnualLeaves = new HashSet<AnnualLeave>();
            this.AnnualLeaves1 = new HashSet<AnnualLeave>();
            this.EmployeeAddresses = new HashSet<EmployeeAddress>();
            this.EmployeeLeaves = new HashSet<EmployeeLeave>();
            this.EmployeeLeaves1 = new HashSet<EmployeeLeave>();
            this.EmployeeRoles = new HashSet<EmployeeRole>();
        }
    
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ICollection<AnnualLeave> AnnualLeaves { get; set; }
        public virtual ICollection<AnnualLeave> AnnualLeaves1 { get; set; }
        public virtual ICollection<EmployeeAddress> EmployeeAddresses { get; set; }
        public virtual ICollection<EmployeeLeave> EmployeeLeaves { get; set; }
        public virtual ICollection<EmployeeLeave> EmployeeLeaves1 { get; set; }
        public virtual ICollection<EmployeeRole> EmployeeRoles { get; set; }
    }
}
